### ISSUE TITLE
Integration "linksys_velop" not found

### ISSUE THREAD

**Issue by russalex** [AdamNaj/linksys_velop#7]
Sometime in the recent past my Hassio / linkssys_velop integration stopped working.  When I perform a "check configuration" it now gives me the error:

> **Platform error device_tracker.linksys_velop - Integration 'linksys_velop' not found.**

Anyone have thoughts? I've tried the usual: reboot, re-install, re-add device_tracker in configuration.yaml.

Steps I used to re-install:
1. Installed this repo using HACS
2. Confirmed directories exist (directories below)
3. Rebooted 
4. Added to the configuration.yaml
5. Configuration -> Configuration validation -> Check Configuration
6. See the error bolded above

Directories:
> custom_components/linksys_velop/__init__.py
> custom_components/linksys_velop/device_tracker.py
> custom_components/linksys_velop/manifest.json
 
Configuration.yaml
```
device_tracker:
  - platform: linksys_velop
    host: 192.168.1.1
    password: !secret linksys_password
    interval_seconds: 30

```
